### ISSUE TITLE
Redirect link to from Google SVN to Github

### ISSUE THREAD

**Issue by schnmudgal** [google/closure-linter#100]
Can you please update your own SVN pages and repositories with guidelines and/or redirection directly to GitHub hosting.
As following is stale now, with not guidelines over there. https://developers.google.com/closure/utilities/docs/linter_howto#install-closure-linter

**Comment by rumpeltux** [comment]
Thanks. Will try to get that site updated.

In the meantime, this should work:

    pip install https://github.com/google/closure-linter/zipball/master

**Comment by rumpeltux** [comment]
Site is updated now.

**Comment by rumpeltux** [comment]
Sorry, to clarify, the update is not yet live, but should be soon.
