### ISSUE TITLE
Ignore folder

### ISSUE THREAD

**Issue by TomBarryy** [google/closure-linter#102]
Could there be a parameter to ignore a specific sub directory when recursively linting?

For example running `gjslint -r RootDirectory --ignore SubDirectoryOne --ignore SubDirectoryTwo` would use the linter on all files in the RootDirectory except for those contained in SubDirectoryOne and SubDirectoryTwo etc.

If this is already a feature can you point me to docs on it's usage?

**Comment by rumpeltux** [comment]
The -r flag is there just for convenience, if you have more complicated logic you’ll need to build the filelist yourself, e.g. using something like `gjslint $(find -path ./ignore -prune -o  -name \*.js)`

**Comment by TomBarryy** [comment]
Ok thanks, I was hoping there would be some in built options for that.
