### ISSUE TITLE
Functions as variables not working

### ISSUE THREAD

**Issue by alexandreStein** [google/closure-linter#107]
I trued to update the package with pip.
It looks like my version is: closure-linter==2.3.19.

If I make a file like this:
```javascript
(function() {
  'use strict';

  let func1 = function anonymous(b) {},
  func2 = function anonymous() {},
  func3 = function() {};
})();
```

When I run the command: ```fixjsstyle --strict file.js```

The resulting file is:
```javascript
(function() {
  'use strict';

  let func1 = function anonymous(b) {};,
  func2 = function anonymous() {};,
  func3 = function() {};
})();
```

It's the same with var:
```javascript
(function() {
  'use strict';

  var func1 = function anonymous(b) {},
  func2 = function anonymous() {},
  func3 = function() {};
})();
```
Which gives:
```javascript
(function() {
  'use strict';

  var func1 = function anonymous(b) {};,
      func2 = function anonymous() {};,
      func3 = function() {};
})();
```

It's maybe not the best way to define functions. But it supposes to works so I guess this is a bug.

By the way, what about to indentation which is not the same with **var** and **let.**

Thanks

**Comment by rumpeltux** [comment]
Unfortunately this project is deprecated (see https://github.com/google/closure-linter/blob/master/README.md)
You can probably try --jslint_error=NO_MISSING_SEMICOLON as a workaround if you still need to use this tool.
